.TH "libchannel-array" 3 "Sat Sep 1 2012" "libchannel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libchannel-array \- 
.PP
Something like type-safe bounded arrays in C\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEFINE_ARRAY\fP(type)   DEFINE_ARRAY_BASE(type, type)"
.br
.RI "\fIDefine struct array_of_[type] and function [type]_array(data, num)\&. \fP"
.ti -1c
.RI "#define \fBDEFINE_STRUCT_ARRAY\fP(type)   DEFINE_ARRAY_BASE(type, struct type)"
.br
.RI "\fI\fBDEFINE_ARRAY\fP for structures\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Something like type-safe bounded arrays in C\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for libchannel from the source code\&.
