.TH "libchannel-message.h" 3 "Sat Sep 1 2012" "libchannel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libchannel-message.h \- 
.PP
Declaration of \fBmessage\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sys/cdefs\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include 'libchannel-array\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBmessage_append_data\fP (struct \fBmessage\fP **m, \fBarray\fP(char))"
.br
.RI "\fIAppend [more] raw data to an existing message\&. \fP"
.ti -1c
.RI "bool \fBmessage_append_descriptors\fP (struct \fBmessage\fP **m, \fBarray\fP(int))"
.br
.RI "\fIAppend [more] descriptors to an existing message\&. \fP"
.ti -1c
.RI "bool \fBmessage_append_channels\fP (struct \fBmessage\fP **m, \fBarray\fP(channelptr))"
.br
.RI "\fIAppend [more] raw data to an existing message\&. \fP"
.ti -1c
.RI "struct \fBmessage\fP * \fBmessage_raw_data\fP (char *data, size_t len)"
.br
.RI "\fIBuild a message that only contains raw data\&. This copies the data\&. \fP"
.ti -1c
.RI "\fBarray\fP (char) message_get_data(struct \fBmessage\fP *)"
.br
.RI "\fIObtain a reference to the raw data contained in a message\&. \fP"
.ti -1c
.RI "\fBarray\fP (int) message_get_descriptors(struct \fBmessage\fP *)"
.br
.RI "\fIObtain a reference to any descriptors contained in a message\&. \fP"
.ti -1c
.RI "size_t \fBmessage_get_channels\fP (struct \fBmessage\fP *)"
.br
.RI "\fIHow many channels does this message hold? \fP"
.ti -1c
.RI "struct \fBchannel\fP * \fBmessage_get_channel\fP (struct \fBmessage\fP *, size_t)"
.br
.RI "\fIRetrieve a particular channel from the message\&. \fP"
.ti -1c
.RI "void \fBmessage_free\fP (struct \fBmessage\fP *)"
.br
.RI "\fIFree a message, including any data it has copied\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Declaration of \fBmessage\fP\&. 


.PP
Definition in file \fBlibchannel-message\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libchannel from the source code\&.
