.TH "Libchannel" 3 "Thu Aug 30 2012" "libchannel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Libchannel \- 
.PP
libchannel provides an abstraction around communication channels like sockets\&.  

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBchannel\fP"
.br
.RI "\fI[opaque] A communications channel for sending data and capabilities (eg file descriptors and channels)\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBchannel\fP * \fBchannel_create\fP (int flags)"
.br
.RI "\fICreate a \fBchannel\fP with certain properties\&. \fP"
.ti -1c
.RI "bool \fBchannel_isvalid\fP (struct \fBchannel\fP *)"
.br
.RI "\fITests the validity of a pointer that claims to be a \fBchannel\fP\&. \fP"
.ti -1c
.RI "void \fBchannel_destroy\fP (struct \fBchannel\fP *c)"
.br
.RI "\fIFree a \fBchannel\fP\&. \fP"
.ti -1c
.RI "int \fBchannel_flags\fP (struct \fBchannel\fP *)"
.br
.RI "\fIGet a channel's flags\&. \fP"
.ti -1c
.RI "int \fBchannel_send\fP (struct \fBchannel\fP *, struct \fBmessage\fP *)"
.br
.RI "\fISend data and/or capabilities over a channel\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
libchannel provides an abstraction around communication channels like sockets\&. 

This allows a message-passing style of interaction, whether the backend is a socket or a function call in the same address space\&. 
.SH "Function Documentation"
.PP 
.SS "struct \fBchannel\fP* channel_create (intflags)\fC [read]\fP"

.PP
Create a \fBchannel\fP with certain properties\&. \fBParameters:\fP
.RS 4
\fIflags\fP any of a number of flags OR'ed together:
.IP "\(bu" 2
CHANNEL_RELIABLE: guarantee reliable delivery
.IP "\(bu" 2
CHANNEL_INORDER: guarantee in-order delivery 
.PP
.RE
.PP

.PP
Definition at line 40 of file libchannel\&.c\&.
.PP
.nf
{
        // TODO: choose among UDS, something else?
        return uds_wrap(uds_create(flags));
}
.fi
.SS "void channel_destroy (struct \fBchannel\fP *c)"

.PP
Free a \fBchannel\fP\&. \fBParameters:\fP
.RS 4
\fIc\fP must be a channel or NULL 
.RE
.PP

.PP
Definition at line 59 of file libchannel\&.c\&.
.PP
References channel_isvalid()\&.
.PP
.nf
{
        assert(channel_isvalid(c));
        free(c);
}
.fi
.SS "int channel_flags (struct \fBchannel\fP *)"

.PP
Get a channel's flags\&. These flags cannot be changed after creation, but they can be retrieved\&.
.PP
\fBReturns:\fP
.RS 4
-1 on error, OR'ed combination of flags otherwise 
.RE
.PP

.PP
Definition at line 66 of file libchannel\&.c\&.
.PP
References channel_isvalid()\&.
.PP
.nf
{
        if (!channel_isvalid(c)) return -1;
        return c->flags;
}
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for libchannel from the source code\&.
