.TH "libchannel-internal.h" 3 "Sat Sep 1 2012" "libchannel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libchannel-internal.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'libchannel\&.h'\fP
.br
\fC#include <stdbool\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBchannel\fP"
.br
.RI "\fI[opaque] A communications channel for sending data and capabilities (eg file descriptors and channels)\&. \fP"
.ti -1c
.RI "struct \fBmessage\fP"
.br
.RI "\fI[opaque] A message that can be sent over a \fBchannel\fP\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBchannel_size\fP (\fBchannel\fP *)"
.br
.RI "\fIHow many bytes does a particular \fBchannel\fP take to store? \fP"
.in -1c
.SH "Detailed Description"
.PP 
Internal definitions for libchannel\&. 
.PP
Definition in file \fBlibchannel-internal\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libchannel from the source code\&.
