.TH "libchannel.h" 3 "Sat Sep 1 2012" "libchannel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libchannel.h \- 
.PP
Public API for libchannel\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sys/cdefs\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include 'libchannel-message\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBchannel\fP * \fBchannel_wrap_socket\fP (int sock)"
.br
.RI "\fICreate a \fBchannel\fP that wraps a UNIX domain socket\&. \fP"
.ti -1c
.RI "bool \fBchannel_isvalid\fP (struct \fBchannel\fP *)"
.br
.RI "\fITests the validity of a pointer that claims to be a \fBchannel\fP\&. \fP"
.ti -1c
.RI "void \fBchannel_destroy\fP (struct \fBchannel\fP *c)"
.br
.RI "\fIFree a \fBchannel\fP\&. \fP"
.ti -1c
.RI "int \fBchannel_send\fP (struct \fBchannel\fP *, struct \fBmessage\fP *)"
.br
.RI "\fISend data and/or capabilities over a channel\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Public API for libchannel\&. 


.PP
Definition in file \fBlibchannel\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libchannel from the source code\&.
