libchannel-message
NAME
libchannel-message -
Abstractions around packet-oriented messages with data, file descriptors and channels.
Data Structures
struct message
[opaque] A message that can be sent over a channel.
Functions
bool message_append_data (struct message **m, array(char))
Append [more] raw data to an existing message.
bool message_append_descriptors (struct message **m, array(int))
Append [more] descriptors to an existing message.
bool message_append_channels (struct message **m, array(channelptr))
Append [more] raw data to an existing message.
struct message * message_raw_data (char *data, size_t len)
Build a message that only contains raw data. This copies the data.
array (char) message_get_data(struct message *)
Obtain a reference to the raw data contained in a message.
array (int) message_get_descriptors(struct message *)
Obtain a reference to any descriptors contained in a message.
size_t message_get_channels (struct message *)
How many channels does this message hold?
struct channel * message_get_channel (struct message *, size_t)
Retrieve a particular channel from the message.
void message_free (struct message *)
Free a message, including any data it has copied.
Detailed Description
Abstractions around packet-oriented messages with data, file descriptors and channels.
Function Documentation
bool message_append_channels (struct message **m, array(channelptr))
Append [more] raw data to an existing message. Parameters:
m the message to append to; will be re-allocated
Returns:
success (true on success, false on failure)
Definition at line 146 of file message.c.
References channel_isvalid(), channel_size(), and message_free().
{
        assert(m != NULL);
        assert(*m != NULL);
        for (size_t i = 0; i < channels.len; i++)
                assert(channel_isvalid(channels.data[i]));
        message *old = *m;
        // Calculate the total size required to store the channels.
        // There is no universal sizeof(channel), so we must enumerate 'em all.
        size_t channel_bytes = 0;
        for (size_t i = 0; i < old->channels.len; i++)
                channel_bytes += channel_size(old->channels.data + i);
        for (size_t i = 0; i < channels.len; i++)
                channel_bytes += channel_size(channels.data[i]);
        message *enlarged = message_realloc(m,
                old->data.len, old->descriptors.len, channel_bytes);
        if (enlarged == NULL) return false;
        *m = enlarged;
        char *new_channels = (char*) enlarged->channels.data;
        char *next = new_channels;
        for (size_t i = 0; i < channels.len; i++) {
                channel *src = channels.data[i];
                int copied = channel_copy(next, src);
                if (copied <= 0) {
                        message_free(enlarged);
                        return -1;
                }
                next += copied;
                enlarged->channels.len++;
        }
        return true;
}
bool message_append_data (struct message **m, array(char))
Append [more] raw data to an existing message. Parameters:
m the message to append to; will be re-allocated
Returns:
success (true on success, false on failure)
Definition at line 108 of file message.c.
{
        assert(m != NULL);
        assert(*m != NULL);
        message old = **m;
        message *enlarged = message_realloc(m,
                old.data.len + data.len, old.descriptors.len, old.channels.len);
        if (enlarged == NULL) return false;
        assert(enlarged->data.len == old.data.len + data.len);
        memcpy(enlarged->data.data + old.data.len, data.data, data.len);
        return true;
}
bool message_append_descriptors (struct message **m, array(int))
Append [more] descriptors to an existing message. Parameters:
m the message to append to; will be re-allocated
Returns:
success (true on success, false on failure)
Definition at line 126 of file message.c.
{
        assert(mp != NULL);
        assert(*mp != NULL);
        message *m = *mp;
        size_t oldcount = m->descriptors.len;
        message *enlarged = message_realloc(mp,
                m->data.len, m->descriptors.len + fds.len, m->channels.len);
        if (enlarged == NULL) return false;
        assert(enlarged->descriptors.len == oldcount + fds.len);
        char *target = (char*) (enlarged->descriptors.data + oldcount);
        memcpy(target, fds.data, fds.len * sizeof(int));
        return true;
}
Author
Generated automatically by Doxygen for libchannel from the source code.