.TH "libchannel-internal.h" 3 "Tue Aug 28 2012" "libchannel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libchannel-internal.h \- 
.PP
Internal definitions for libchannel\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'libchannel\&.h'\fP
.br
\fC#include <stdbool\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBchannel\fP"
.br
.RI "\fIA communications channel for sending data and capabilities (eg file descriptors and channels)\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Internal definitions for libchannel\&. 


.PP
Definition in file \fBlibchannel-internal\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libchannel from the source code\&.
