.TH "libchannel.c" 3 "Sat Sep 1 2012" "libchannel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libchannel.c \- 
.PP
Implementation of platform-portable parts\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'libchannel\&.h'\fP
.br
\fC#include 'libchannel-internal\&.h'\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBchannel_size\fP (\fBchannel\fP *c)"
.br
.RI "\fIHow many bytes does a particular \fBchannel\fP take to store? \fP"
.ti -1c
.RI "\fBchannel\fP * \fBchannel_wrap_socket\fP (int sock)"
.br
.RI "\fICreate a \fBchannel\fP that wraps a UNIX domain socket\&. \fP"
.ti -1c
.RI "bool \fBchannel_isvalid\fP (\fBchannel\fP *c)"
.br
.RI "\fITests the validity of a pointer that claims to be a \fBchannel\fP\&. \fP"
.ti -1c
.RI "void \fBchannel_destroy\fP (\fBchannel\fP *c)"
.br
.RI "\fIFree a \fBchannel\fP\&. \fP"
.ti -1c
.RI "int \fBchannel_send\fP (struct \fBchannel\fP *c, struct \fBmessage\fP *m)"
.br
.RI "\fISend data and/or capabilities over a channel\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Implementation of platform-portable parts\&. 


.PP
Definition in file \fBlibchannel\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libchannel from the source code\&.
