.TH "libchannel-array.h" 3 "Sat Sep 1 2012" "libchannel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libchannel-array.h \- 
.PP
Something like bounded type-safe arrays in C\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sys/cdefs\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEFINE_ARRAY\fP(type)   DEFINE_ARRAY_BASE(type, type)"
.br
.RI "\fIDefine struct array_of_[type] and function [type]_array(data, num)\&. \fP"
.ti -1c
.RI "#define \fBDEFINE_STRUCT_ARRAY\fP(type)   DEFINE_ARRAY_BASE(type, struct type)"
.br
.RI "\fI\fBDEFINE_ARRAY\fP for structures\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Something like bounded type-safe arrays in C\&. 


.PP
Definition in file \fBlibchannel-array\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libchannel from the source code\&.
