.TH "message.c" 3 "Sat Sep 1 2012" "libchannel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
message.c \- 
.PP
Implementation of the \fBmessage\fP abstraction\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'libchannel\&.h'\fP
.br
\fC#include 'libchannel-internal\&.h'\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmessage_free\fP (struct \fBmessage\fP *m)"
.br
.RI "\fIFree a message, including any data it has copied\&. \fP"
.ti -1c
.RI "bool \fBmessage_append_data\fP (\fBmessage\fP **m, \fBarray\fP(char) data)"
.br
.RI "\fIAppend [more] raw data to an existing message\&. \fP"
.ti -1c
.RI "bool \fBmessage_append_descriptors\fP (\fBmessage\fP **mp, \fBarray\fP(int) fds)"
.br
.RI "\fIAppend [more] descriptors to an existing message\&. \fP"
.ti -1c
.RI "bool \fBmessage_append_channels\fP (\fBmessage\fP **m, \fBarray\fP(channelptr) channels)"
.br
.RI "\fIAppend [more] raw data to an existing message\&. \fP"
.ti -1c
.RI "struct \fBmessage\fP * \fBmessage_raw_data\fP (char *data, size_t len)"
.br
.RI "\fIBuild a message that only contains raw data\&. This copies the data\&. \fP"
.ti -1c
.RI "\fBarray\fP (char)"
.br
.RI "\fIObtain a reference to the raw data contained in a message\&. \fP"
.ti -1c
.RI "\fBarray\fP (int)"
.br
.RI "\fIObtain a reference to any descriptors contained in a message\&. \fP"
.ti -1c
.RI "size_t \fBmessage_get_channels\fP (struct \fBmessage\fP *m)"
.br
.RI "\fIHow many channels does this message hold? \fP"
.ti -1c
.RI "\fBchannel\fP * \fBmessage_get_channel\fP (struct \fBmessage\fP *m, size_t index)"
.br
.RI "\fIRetrieve a particular channel from the message\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Implementation of the \fBmessage\fP abstraction\&. 


.PP
Definition in file \fBmessage\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libchannel from the source code\&.
