.TH "message" 3 "Sat Sep 1 2012" "libchannel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
message \- 
.PP
[opaque] A message that can be sent over a \fBchannel\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'libchannel-message\&.h'\fP
.SH "Detailed Description"
.PP 
[opaque] A message that can be sent over a \fBchannel\fP\&. 

A message can incorporate raw data, file descriptors and other channels\&. 
.PP
Definition at line 75 of file libchannel-internal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libchannel from the source code\&.
